name: Release Packages
on:
  workflow_dispatch:
    inputs:
      method:
        description: |
          Which number to increment in the semantic versioning.
        required: true
        type: choice
        options:
          - major
          - minor
          - patch
        default: minor

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@master

      - name: Bump-up Semantic Version
        uses: kyoh86/git-vertag-action@v1.1
        with:
          method: "${{ github.event.inputs.method }}"

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --config .goreleaser.yml
